Traceback (most recent call last):
  File "/opt/conda/envs/idm/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/idm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/oracle/Research-Papers-Implementation/SRGAN/train/srresnet.py", line 63, in <module>
    train(model, train_loader, optimizer, criterion, num_epochs)
  File "/home/ubuntu/oracle/Research-Papers-Implementation/SRGAN/train/srresnet.py", line 48, in train
    lr_images,hr_images = lr_images.to(device), hr_images.to(device)
AttributeError: 'str' object has no attribute 'to'
Traceback (most recent call last):
  File "/opt/conda/envs/idm/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/idm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/oracle/Research-Papers-Implementation/SRGAN/train/srresnet.py", line 63, in <module>
    train(model, train_loader, optimizer, criterion, num_epochs)
  File "/home/ubuntu/oracle/Research-Papers-Implementation/SRGAN/train/srresnet.py", line 48, in train
    lr_images,hr_images = lr_images.to(device), hr_images.to(device)
AttributeError: 'str' object has no attribute 'to'
